### ISSUE TITLE
Error while using GPU

### ISSUE THREAD

**Issue by Cryptonean** [FareedKhan-dev/yolov7-face-blur#1]
I was using detect.py for the video blur. Firstly i use CPU its was running smoothely but later on i use GPU for the same video , but in between it showed error and got terminated.
And yes i have installed all the requirements.

ERROR = 
 line 126, in detect
    blur = cv2.blur(crop_obj,(blurratio,blurratio))
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\box_filter.dispatch.cpp:446: error: (-215:Assertion failed) !_src.empty() in function 'cv::boxFilter'

**Comment by FareedKhan-dev** [comment]
I have just reused this repository, and it is currently working properly. Make sure to double-check the following steps:

1. To use the GPU, install the required packages using `pip install -r requirements_gpu.txt`.
2. When using the GPU, use the following command:
`python detect.py --weights yolov7-tiny.pt --blurratio 50 --device 0 --source 2.mp4`
Set the device to 0 to utilize the GPU.
3. Ensure that the video is present in the directory. 
4. Verify that the `blurratio` variable is correctly set to a positive integer that makes sense for blurring.
